export const bookingData = [
  {
    id: 1,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Change departure date",
    status: "Pending",
    color: '#112345'
  },
  {
    id: 2,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Change departure date",
    status: "Processed",
  },
  {
    id: 3,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Cancel",
    status: "Pending",
  },
  {
    id: 4,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Cancel",
    status: "Pending",
  },
  {
    id: 5,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Change departure date",
    status: "Pending",
  },
  {
    id: 6,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Change departure date",
    status: "Pending",
  },
  {
    id: 7,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Change departure date",
    status: "Pending",
  },
  {
    id: 8,
    email: "hello@trip2.com",
    phone: "0123456789",
    package: "Ambassador Cruise",
    request: "Change departure date",
    status: "Pending",
  },
];
